source "https://rubygems.org"

gem "jekyll"
gem "jekyll_ext"
gem "liquid"
gem "rdiscount"
gem "nokogiri"
gem "jekyll-speakerdeck", git: "git://github.com/flyerhzm/jekyll-speakerdeck.git"
gem "capistrano"
gem "capistrano-bundler"
gem "capistrano-rvm"
